---
- name: Installing Kibana.
  sudo: yes
  yum: name=kibana  state=present

- name: Copy Configuration file for Kibana3
  copy: src=../files/kibana3.conf dest=/etc/httpd/conf.d/kibana3.conf 
  notify: restart apache

- name: Disable SELinux
  sudo: yes
  service: enabled=no  name=selinux  state=stopped
  notify: restart apache

- name: ensure python-selinux is installed on all nodes.
  action: yum name=libselinux-python state=installed  

- name: set SELinux to permissive
  action: selinux policy=targeted state=permissive

- name: Create a copy of Kibana Default Dashboards.
  sudo: yes
  command: mv /usr/share/kibana/app/dashboards/default.json /usr/share/kibana/app/dashboards/default_2.json

- name: Configure Kibana
  template: src=kibana_default.json dest=/usr/share/kibana/app/dashboards/default.json
  notify: restart apache